### ISSUE TITLE
Incorporate polysemy information

### ISSUE THREAD

**Issue by fcbr** [fcbr/cl-wnbrowser#103] opened 2015-05-24 19:59 UTC
per @vcvpaiva

Need to define how to incorporate this into the current UI / db.

**Comment by arademaker** [comment] 2015-05-25 14:19
More info would be nice here. I didn't understand the request.

**Comment by vcvpaiva** [comment] 2015-05-26 15:33
According to https://www.aclweb.org/anthology/W/W14/W14-0102.pdf
PWN has
118.695 synsets
206.979 words.
 82.3 % of synsets is monossemic= 97,329 synsets.
But when using OWN-PT  and investigating PWN I find only 63,848 synsets with a single word.  
This is  not a problem per se, but it would be good to know _which_ ones are the monosemic synsets in English and  whether they are the same as the ones in Portuguese. This will help establish mappings from English to Portuguese and other languages, as monosemic synsets are very easy to translate. the problem is to discover how many they are and how polysemic the rest of the synsets are.

**Comment by arademaker** [comment] 2019-10-06 19:08
It is not clear what is this issue. I am closing it but will open one about the last comment from valeria

**Closed as completed by arademaker** 2019-10-06 19:08 UTC
